Drupal-NYC/drupalcampnyc

- themes/custom/dcnyc/css/buttonssk.css
- themes/custom/dcnyc/css/components/form.css
- themes/custom/dcnyc/css/dcnyc.css
1. Contact page has style issues on iphone #23
2. Place CTA buttons side by side not stacked ("register" should be on the left) #32
3. on home page, main (featured) content head is indenting #37
4. sitewide: footer issues (see below) #38
> misc fixes

- composer.lock
symfony/filesystem (v3.4.20 => v3.4.22)
symfony/config (v3.4.20 => v3.4.22)
consolidation/config (1.1.1 => 1.2.0)
consolidation/annotated-command (2.11.0 => 2.11.2)
consolidation/robo (1.4.3 => 1.4.6)
drupal/google_analytics (2.3.0 => 2.4.0)
symfony/cache (v3.4.20 => v3.4.22)
stecman/symfony-console-completion (0.8.0 => 0.9.0)
nikic/php-parser (v4.1.1 => v4.2.1)
symfony/var-dumper (v3.4.20 => v3.4.22)
chi-teck/drupal-code-generator (1.27.0 => 1.28.0)
> General update to dependencies:

- codeship-steps.yml
- composer.json
- scripts/robo/BallastRunner.php
- scripts/robo/src/Commands/DeployCommands.php
- scripts/robo/src/Commands/FrontEndTrait.php
- scripts/robo/src/Commands/RemoteRebuildCommands.php
- scripts/robo/src/Commands/SetupCommands.php
- setup/docker/docker-compose-template
The Ballast code was 7 versions behind.  This PR updates to the current version, minus some git unshallow logic for Bitbucket/Acquia compatibility.
> Update Ballast to the less intrusive v14

- web/themes/drupaleurope/assets/css/_variables.scss
- web/themes/drupaleurope/assets/css/components/_buttons.scss
- web/themes/drupaleurope/assets/css/main.scss
- web/themes/drupalnyc/assets/css/_variables.scss
- web/themes/drupalnyc/assets/css/components/_buttons.scss
- web/themes/drupalnyc/assets/css/main.scss
Button mixins created for markup created buttons using bootstrap-like syntax:
&lt;a class="btn btn-color-1 btn-lg" href="#"&gt;
using Primary, Secondary, Tertiary colors as defined in drupaleurope/assets/css/_variables.scss
Also, Tweak to Deck > Element - Call to action Button style
/web/themes/drupaleurope/build/ is in the git ignore
I'm not sure what the process is for getting this into production?
> issue #118 buttons

- config/core.entity_view_display.node.sponsor.default.yml
- web/themes/drupalnyc/assets/css/components/_sponsors.scss
logo size now defined in css w/media query
> 147 sponosor logo responsiveness

- web/themes/drupalnyc/assets/css/components/_buttons.scss
- web/themes/drupalnyc/assets/css/components/_decks.scss
- web/themes/drupalnyc/assets/css/components/_header.scss
- web/themes/drupalnyc/assets/css/components/decks/_hero.scss
> init of 155-homepage-fixes

- config/block.block.views_block__sponsors_block_venue_2.yml
> Remove venue sponsor from footer

- config/system.performance.yml
> Fixes #160: Enable core CSS and JS aggregation

- config/field.field.node.sponsor.field_sponsor_priority.yml
- config/field.storage.node.field_level.yml
- config/views.view.sponsors.yml
- web/themes/drupalnyc/assets/css/components/_sponsors.scss
> #170 Add in-kind sponsorship tier

- web/themes/drupalnyc/assets/css/components/_header.scss
- web/themes/drupalnyc/assets/css/components/_menu.scss
> slogan resize and position, misc admin nav tweaks

- drush/drush.yml
Just like it says on the tin.
This is a test PR just to verify that I can, indeed, create a PR for this project.
Also, `lando drush uli` should just work in local dev environment without requiring additional arguments.
> Add drush.yml so drush uli works correctly.

- web/sites/default/settings.php
Temporarily disable the redirect from Pantheon Live domain to static site.
> Set $primary_domain to Pantheon Live.

- config/message_banner.settings.yml
> #192: Disable message banner

- config/system.site.yml
> #195 change site slogan

- web/themes/drupalnyc/drupalnyc.info.yml
- web/themes/drupalnyc/templates/layout/page--node.html.twig
- web/themes/drupalnyc/templates/layout/page.html.twig
> #198 Update footer and misc. instances of 2020 to 2021

- config/system.site.yml
> #200: Tweak site slogan

- web/sites/default/settings.php
Fixes #202 
Waiting to merge until we're ready to go live.
> #202: Redirect bare domain and www to 2021 subdomain

- .lando.yml
- pantheon.yml
> #209: Upgrade to MariaDB 10.4

- config/views.view.sponsors.yml
> #216: Sponsors don't appear in correct order

- web/modules/custom/sessionize_embed_block/src/Plugin/Block/SessionizeEmbedBlock.php
- web/modules/custom/sessionize_embed_block/src/Sessionize/Embed.php
> Fix config bug.
